spring:
  datasource:
    url: jdbc:mysql://localhost:3310/internship
    username: admin
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secret: 4oCYc3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LWhhbmdoYWUtYXNzaWdubWVudC1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3Qtc2VjcmV0LWtleeKAmQo=

